# %% [markdown]
# # 10 — Final Report Generation
#
# Assembles figures/tables already produced under results/ into
# docs/final_report.md. Adds no new computation, per Section 4.1 of the
# build spec.

import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

FIG_DIR = REPO_ROOT / "results" / "figures"
TABLE_DIR = REPO_ROOT / "results" / "tables"
REPORT_PATH = REPO_ROOT / "docs" / "final_report.md"

HEADER = """# Final Report — Reproduction of Siddagangaiah et al. (2020)

*Generated by `notebooks/10_final_report_generation.py` on {timestamp}.
This notebook performs no new computation -- it only assembles figures and
tables already produced under `results/` by notebooks 02-09.*

## Headline statement

**This is not a full reproduction of the paper's results.** We built
faithful, from-scratch implementations of both entropy metrics (H, SE) and
validated them exactly against the paper's own worked example. We
qualitatively confirmed H/SE behavior on the 8 publicly available short WAV
clips (where present in `data/raw/` at generation time). We did **not**
reproduce the paper's headline >95% detection accuracy figures or Pearson
correlations, because those require long-duration recordings and manual
annotation vectors that are not available in this environment (see
`docs/reproduction_audit.md` and `docs/author_correspondence.md`).

## What was reproduced

- Permutation entropy (H), computed from scratch per Eqs. (1)-(4),
  reproduces the paper's own worked example exactly: `(7,3,4,5)->(3,0,1,2)`,
  `(3,4,5,2)->(1,2,3,0)`.
- Sample entropy (SE), computed from scratch per Eqs. (5)-(12), matches an
  independent brute-force cross-check exactly.
- Synthetic sanity-ordering checks for both metrics (see
  `docs/reproduction_audit.md`).
- The full long-duration detrend/threshold/count pipeline and the
  confusion-matrix/accuracy pipeline, both validated end-to-end against
  synthetic placeholder data with known ground truth.

## What remains BLOCKED

- Table 1's exact confusion matrices and accuracy/error-rate figures.
- The Pearson correlation figures (whistle-density, click-density).
- Figs. 1, 2, 6, 7's on/off detection dynamic on long recordings.

See `docs/reproduction_audit.md` for the complete, up-to-date audit and
`docs/author_correspondence.md` for the draft data request to the
corresponding authors.

"""

FOOTER_IF_NO_DATA = """
## Figures and tables

No entries found under `results/figures/` or `results/tables/` beyond
what the algorithm-validation notebooks (03, 04, 07, 08, 09) produce
without real audio. Download the 8 WAV files (see `data/raw/SOURCE.md`)
and re-run `notebooks/02` through `notebooks/09` against real audio, then
re-run this notebook, to populate a full figures/tables section here.
"""


def collect_generated_assets():
    figs = sorted(FIG_DIR.glob("*.png")) if FIG_DIR.exists() else []
    tables = sorted(TABLE_DIR.glob("*.csv")) if TABLE_DIR.exists() else []
    return figs, tables


def build_report_body(figs, tables) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = HEADER.format(timestamp=timestamp)

    if not figs and not tables:
        body += FOOTER_IF_NO_DATA
        return body

    body += "## Figures and tables\n\n"
    if tables:
        body += "### Tables\n\n"
        for t in tables:
            body += f"- `{t.relative_to(REPO_ROOT)}`\n"
        body += "\n"
    if figs:
        body += "### Figures\n\n"
        for f in figs:
            body += f"- `{f.relative_to(REPO_ROOT)}`\n"
        body += "\n"
    return body


def main():
    figs, tables = collect_generated_assets()
    report = build_report_body(figs, tables)
    REPORT_PATH.write_text(report)
    print(f"Wrote {REPORT_PATH} ({len(figs)} figures, {len(tables)} tables referenced).")
    if not figs and not tables:
        print(
            "No generated figures/tables found -- this report currently "
            "documents status only. Run notebooks 02-09 against real audio "
            "(see data/raw/SOURCE.md) and re-run this notebook for a full report."
        )


if __name__ == "__main__":
    main()
